default: &default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: db/portfolio-dev.sqlite3

production:
  <<: *default
  database: db/portfolio-prod.db

# test:
#   <<: *default
#   database: db/todos-test.sqlite3